name: Onyou_CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execution permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_JJUNYONG_ONYOU }}

      - name: Docker Build and push (main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t onyou .
          docker tag onyou ${{ secrets.DOCKER_USERNAME }}/onyou:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKER_USERNAME }}/onyou:${GITHUB_SHA::7}

      - name: Docker Build and push (develop branch)
        if: github.ref == 'refs/heads/develop'
        run: |
          docker build -t onyou-dev .
          docker tag onyou-dev ${{ secrets.DOCKER_USERNAME }}/onyou-dev:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKER_USERNAME }}/onyou-dev:${GITHUB_SHA::7}
